"use client";

import React, { useState, useCallback } from "react";
import Link from "next/link";
import { 
  Scale, LayoutDashboard, BarChart2, PieChart, Network, 
  AlertTriangle, Share2, Download, AlertCircle, FileText, CheckCircle2,
  Check, Copy, Printer
} from "lucide-react";
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Cell
} from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useAuditStore } from "@/store/auditStore";

export default function ReportPage() {
  const { auditResult, filename, targetColumn, sensitiveAttribute } = useAuditStore();
  const [shareStatus, setShareStatus] = useState<"idle" | "copied">("idle");

  // ── Share handler ──────────────────────────────────────────────────
  const handleShare = useCallback(async () => {
    const shareData = {
      title: `FairSight Audit Report — ${filename}`,
      text: `Audit results for ${filename}: Disparate Impact Ratio ${auditResult?.disparate_impact_ratio.toFixed(3)}, Health Score ${auditResult?.health_score}/100. ${auditResult?.bias_detected ? "⚠️ Bias Detected" : "✅ Fair"}`,
      url: window.location.href,
    };

    // Try native Web Share API first (works on mobile & some desktop browsers)
    if (navigator.share && navigator.canShare?.(shareData)) {
      try {
        await navigator.share(shareData);
        return;
      } catch {
        // User cancelled or API failed — fall through to clipboard
      }
    }

    // Fallback: copy a rich text summary to clipboard
    const summaryText = [
      `📊 FairSight Bias Audit Report`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `File: ${filename}`,
      `Target: ${targetColumn}`,
      `Sensitive Attribute: ${sensitiveAttribute}`,
      ``,
      `Disparate Impact Ratio: ${auditResult?.disparate_impact_ratio.toFixed(4)}`,
      `Demographic Parity Difference: ${auditResult?.demographic_parity_difference.toFixed(4)}`,
      `Equalized Odds Difference: ${auditResult?.equalized_odds_difference.toFixed(4)}`,
      `Overall Accuracy: ${((auditResult?.overall_accuracy ?? 0) * 100).toFixed(1)}%`,
      `Health Score: ${auditResult?.health_score}/100`,
      `Status: ${auditResult?.bias_detected ? "⚠️ BIAS DETECTED" : "✅ FAIR"}`,
      ``,
      `Selection Rates:`,
      ...Object.entries(auditResult?.selection_rates ?? {}).map(
        ([group, rate]) => `  • ${group}: ${(rate * 100).toFixed(1)}%`
      ),
      ``,
      `Top Features (SHAP):`,
      ...(auditResult?.shap_features ?? []).map(
        (f) => `  • ${f.feature}: ${f.importance.toFixed(4)} (${f.direction})`
      ),
      ``,
      `AI Insight:`,
      auditResult?.gemini_insight || "N/A",
      ``,
      `Generated by FairSight — ${window.location.origin}`,
    ].join("\n");

    try {
      await navigator.clipboard.writeText(summaryText);
      setShareStatus("copied");
      setTimeout(() => setShareStatus("idle"), 2500);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = summaryText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setShareStatus("copied");
      setTimeout(() => setShareStatus("idle"), 2500);
    }
  }, [auditResult, filename, targetColumn, sensitiveAttribute]);

  // ── Export PDF handler ─────────────────────────────────────────────
  const handleExportPDF = useCallback(() => {
    window.print();
  }, []);

  if (!auditResult) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-6 text-center space-y-6">
        <AlertCircle className="h-16 w-16 text-muted-foreground mb-4" />
        <h1 className="text-3xl font-bold">No Audit Data Found</h1>
        <p className="text-muted-foreground max-w-md">
          It looks like you haven&apos;t run an audit yet, or your session has expired.
        </p>
        <Link href="/">
          <Button size="lg" className="mt-4">Run a New Audit</Button>
        </Link>
      </div>
    );
  }

  const isBiased = auditResult.bias_detected;
  const statusColor = isBiased ? "bg-destructive text-destructive-foreground" : "bg-success text-success-foreground";
  const statusText = isBiased ? "BIAS DETECTED" : "FAIR";

  // Format data for Outcome Rates chart
  const outcomeData = Object.entries(auditResult.selection_rates).map(([group, rate]) => ({
    group,
    rate: Number((rate * 100).toFixed(1)),
  })).sort((a, b) => b.rate - a.rate);

  // Format data for SHAP chart
  const shapData = auditResult.shap_features.slice(0, 5).map(f => ({
    name: f.feature,
    value: Number(f.importance.toFixed(3)),
  })).sort((a, b) => b.value - a.value);

  return (
    <div className="flex min-h-screen bg-background">
      {/* Left Sidebar — hidden during print */}
      <aside className="w-64 fixed inset-y-0 left-0 bg-card border-r border-border hidden lg:flex flex-col z-10 print:hidden">
        <div className="p-6">
          <Link href="/" className="flex items-center gap-2 text-primary font-bold text-xl mb-8">
            <Scale className="h-6 w-6" />
            <span>FairSight</span>
          </Link>
          
          <nav className="space-y-1">
            <a href="#overview" className="flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-md bg-primary/10 text-primary">
              <LayoutDashboard className="h-4 w-4" /> Overview
            </a>
            <a href="#disparate-impact" className="flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-colors">
              <PieChart className="h-4 w-4" /> Disparate Impact
            </a>
            <a href="#statistical-parity" className="flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-colors">
              <BarChart2 className="h-4 w-4" /> Statistical Parity
            </a>
            <a href="#feature-analysis" className="flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-colors">
              <Network className="h-4 w-4" /> Feature Analysis
            </a>
            <a href="#recommendations" className="flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-colors">
              <AlertTriangle className="h-4 w-4" /> Recommendations
            </a>
          </nav>
        </div>

        <div className="mt-auto p-6 space-y-4">
          <Separator className="bg-border" />
          <div>
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Audit Info</h4>
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2 text-foreground font-mono truncate">
                <FileText className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                <span className="truncate" title={filename || ""}>{filename}</span>
              </div>
              <div className="text-muted-foreground pl-6 text-xs">
                {new Date().toLocaleDateString()}
              </div>
              <div className="pl-6 mt-2">
                <Badge variant="outline" className={`${statusColor} border-none text-xs font-bold`}>
                  {statusText}
                </Badge>
              </div>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 lg:pl-64 flex flex-col print:pl-0">
        <div className="max-w-6xl mx-auto w-full p-6 lg:p-10 space-y-10">
          
          {/* Print-only header (shown in PDF only) */}
          <div className="hidden print:block print:mb-6">
            <div className="flex items-center gap-2 text-2xl font-bold mb-2">
              <Scale className="h-7 w-7" />
              FairSight — Bias Audit Report
            </div>
            <div className="text-sm text-gray-600 space-y-1">
              <p>File: {filename} • Date: {new Date().toLocaleDateString()}</p>
              <p>Target: {targetColumn} • Sensitive Attribute: {sensitiveAttribute}</p>
              <p className="font-bold">{isBiased ? "⚠ BIAS DETECTED" : "✓ FAIR"}</p>
            </div>
          </div>

          {/* Header */}
          <header className="flex flex-col md:flex-row md:items-start justify-between gap-4 print:hidden">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h1 className="text-3xl font-bold tracking-tight">Audit Report</h1>
                <Badge variant="outline" className={`${statusColor} border-none`}>
                  {statusText}
                </Badge>
              </div>
              <p className="text-muted-foreground font-medium">
                Target: <span className="text-foreground font-mono">{targetColumn}</span> • 
                Sensitive Attribute: <span className="text-foreground font-mono">{sensitiveAttribute}</span>
              </p>
            </div>
            <div className="flex items-center gap-3">
              <Button
                variant="outline"
                className="border-border hover:bg-muted"
                onClick={handleShare}
              >
                {shareStatus === "copied" ? (
                  <>
                    <Check className="h-4 w-4 mr-2 text-success" /> Copied!
                  </>
                ) : (
                  <>
                    <Share2 className="h-4 w-4 mr-2" /> Share
                  </>
                )}
              </Button>
              <Button
                className="bg-primary text-primary-foreground hover:bg-primary/90"
                onClick={handleExportPDF}
              >
                <Download className="h-4 w-4 mr-2" /> Export PDF
              </Button>
            </div>
          </header>

          {/* Metric Cards */}
          <section id="overview" className="grid grid-cols-1 md:grid-cols-3 gap-6 print:grid-cols-3">
            <Card className="bg-card border-border print:border print:border-gray-300">
              <CardHeader className="pb-2 flex flex-row items-center justify-between">
                <CardTitle className="text-sm font-medium text-muted-foreground">Disparate Impact Ratio</CardTitle>
                <Tooltip>
                  <TooltipTrigger>
                    <AlertCircle className="h-4 w-4 text-muted-foreground print:hidden" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p className="max-w-xs text-xs">Ratio of favorable outcomes for the unprivileged group compared to the privileged group. Values &lt; 0.8 indicate potential bias.</p>
                  </TooltipContent>
                </Tooltip>
              </CardHeader>
              <CardContent>
                <div className={`text-4xl font-mono font-bold ${auditResult.disparate_impact_ratio < 0.8 ? "text-destructive print:text-red-600" : "text-success print:text-green-600"}`}>
                  {auditResult.disparate_impact_ratio.toFixed(3)}
                </div>
                <p className="text-xs text-muted-foreground mt-2">
                  Target threshold: &ge; 0.800
                </p>
              </CardContent>
            </Card>

            <Card className="bg-card border-border print:border print:border-gray-300">
              <CardHeader className="pb-2 flex flex-row items-center justify-between">
                <CardTitle className="text-sm font-medium text-muted-foreground">Statistical Parity Gap</CardTitle>
                <Tooltip>
                  <TooltipTrigger>
                    <AlertCircle className="h-4 w-4 text-muted-foreground print:hidden" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p className="max-w-xs text-xs">The absolute difference in selection rates between different groups. Lower is better.</p>
                  </TooltipContent>
                </Tooltip>
              </CardHeader>
              <CardContent>
                <div className="text-4xl font-mono font-bold text-foreground print:text-black">
                  {auditResult.demographic_parity_difference.toFixed(3)}
                </div>
                <p className="text-xs text-muted-foreground mt-2">
                  Target threshold: &le; 0.100
                </p>
              </CardContent>
            </Card>

            <Card className="bg-card border-border print:border print:border-gray-300">
              <CardHeader className="pb-2 flex flex-row items-center justify-between">
                <CardTitle className="text-sm font-medium text-muted-foreground">Dataset Health Score</CardTitle>
                <Tooltip>
                  <TooltipTrigger>
                    <AlertCircle className="h-4 w-4 text-muted-foreground print:hidden" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p className="max-w-xs text-xs">Overall fairness score based on aggregated bias metrics.</p>
                  </TooltipContent>
                </Tooltip>
              </CardHeader>
              <CardContent className="flex items-center gap-4">
                {/* Simple Circular Progress implementation */}
                <div className="relative h-16 w-16 flex items-center justify-center">
                  <svg className="h-full w-full transform -rotate-90" viewBox="0 0 36 36">
                    <path
                      className="text-muted stroke-current"
                      strokeWidth="4"
                      fill="none"
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    />
                    <path
                      className={`${
                        auditResult.health_score >= 80 ? "text-success" : 
                        auditResult.health_score >= 60 ? "text-warning" : "text-destructive"
                      } stroke-current`}
                      strokeWidth="4"
                      strokeDasharray={`${auditResult.health_score}, 100`}
                      fill="none"
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    />
                  </svg>
                  <span className="absolute text-lg font-bold font-mono">
                    {Math.round(auditResult.health_score)}
                  </span>
                </div>
                <div className="text-sm text-muted-foreground">
                  Out of 100
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Print-only data table (replaces charts in PDF since Recharts doesn't render in print) */}
          <div className="hidden print:block space-y-6">
            <div>
              <h3 className="text-lg font-bold mb-2">Outcome Rates by Group</h3>
              <table className="w-full border-collapse border border-gray-300 text-sm">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 px-3 py-2 text-left">Group</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Positive Rate</th>
                  </tr>
                </thead>
                <tbody>
                  {outcomeData.map((entry) => (
                    <tr key={entry.group}>
                      <td className="border border-gray-300 px-3 py-2">{entry.group}</td>
                      <td className="border border-gray-300 px-3 py-2">{entry.rate}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div>
              <h3 className="text-lg font-bold mb-2">Top Bias-Contributing Features (SHAP)</h3>
              <table className="w-full border-collapse border border-gray-300 text-sm">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 px-3 py-2 text-left">Feature</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Importance</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Direction</th>
                  </tr>
                </thead>
                <tbody>
                  {auditResult.shap_features.slice(0, 5).map((f) => (
                    <tr key={f.feature}>
                      <td className="border border-gray-300 px-3 py-2">{f.feature}</td>
                      <td className="border border-gray-300 px-3 py-2">{f.importance.toFixed(4)}</td>
                      <td className="border border-gray-300 px-3 py-2">{f.direction === "increases_bias" ? "⚠ Increases Bias" : "Neutral"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Screen-only charts */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 print:hidden">
            {/* Outcome Rates Chart */}
            <Card id="disparate-impact" className="bg-card border-border">
              <CardHeader>
                <CardTitle className="text-lg">Outcome Rates by Group</CardTitle>
                <p className="text-sm text-muted-foreground">Positive outcome % for each value in {sensitiveAttribute}</p>
              </CardHeader>
              <CardContent className="h-80">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={outcomeData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#2D3748" />
                    <XAxis type="number" domain={[0, 100]} tick={{ fill: '#94a3b8' }} tickFormatter={(val) => `${val}%`} />
                    <YAxis dataKey="group" type="category" tick={{ fill: '#ffffff', fontSize: 12 }} width={80} />
                    <RechartsTooltip 
                      cursor={{fill: '#2D3748', opacity: 0.4}}
                      contentStyle={{ backgroundColor: '#1A1D27', borderColor: '#2D3748', color: '#fff' }}
                      formatter={(value) => [`${value}%`, 'Positive Rate']}
                    />
                    <Bar dataKey="rate" radius={[0, 4, 4, 0]}>
                      {outcomeData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={index === 0 ? '#3B82F6' : index === outcomeData.length - 1 ? '#EF4444' : '#64748b'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* SHAP Values Chart */}
            <Card id="feature-analysis" className="bg-card border-border">
              <CardHeader>
                <CardTitle className="text-lg">Top Bias-Contributing Features</CardTitle>
                <p className="text-sm text-muted-foreground">Features ranked by SHAP importance</p>
              </CardHeader>
              <CardContent className="h-80">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={shapData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#2D3748" />
                    <XAxis type="number" tick={{ fill: '#94a3b8' }} />
                    <YAxis dataKey="name" type="category" tick={{ fill: '#ffffff', fontSize: 12 }} width={80} />
                    <RechartsTooltip 
                      cursor={{fill: '#2D3748', opacity: 0.4}}
                      contentStyle={{ backgroundColor: '#1A1D27', borderColor: '#2D3748', color: '#fff' }}
                    />
                    <Bar dataKey="value" fill="#3B82F6" radius={[0, 4, 4, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          {/* AI Insight */}
          <section>
            <Card className="bg-primary/5 border-primary shadow-lg shadow-primary/5 print:bg-blue-50 print:border-blue-300 print:shadow-none">
              <CardContent className="p-6">
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-primary/20 rounded-lg print:bg-blue-100">
                      <LayoutDashboard className="h-6 w-6 text-primary print:text-blue-600" />
                    </div>
                    <h3 className="text-xl font-bold">AI Insight</h3>
                  </div>
                  <Badge variant="outline" className="border-primary text-primary bg-primary/10 print:border-blue-400 print:text-blue-600">
                    Generated by Gemini AI
                  </Badge>
                </div>
                <div className="prose prose-invert max-w-none text-foreground/90 print:prose print:text-black">
                  <p className="leading-relaxed whitespace-pre-wrap">
                    {auditResult.gemini_insight || "No insights generated for this dataset."}
                  </p>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Recommendations */}
          <section id="recommendations" className="space-y-6">
            <h3 className="text-xl font-bold border-b border-border pb-2">Recommendations</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 print:grid-cols-3">
              <Card className="bg-card border-border print:border print:border-gray-300">
                <CardHeader className="pb-3">
                  <AlertTriangle className="h-8 w-8 text-warning mb-2 print:text-amber-500" />
                  <CardTitle className="text-base font-bold">Apply Dataset Reweighing</CardTitle>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground leading-relaxed print:text-gray-600">
                  Rebalance outcome distribution across {sensitiveAttribute} groups before retraining to mitigate disparate impact.
                </CardContent>
              </Card>

              <Card className="bg-card border-border print:border print:border-gray-300">
                <CardHeader className="pb-3">
                  <AlertTriangle className="h-8 w-8 text-warning mb-2 print:text-amber-500" />
                  <CardTitle className="text-base font-bold">Remove Proxy Features</CardTitle>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground leading-relaxed print:text-gray-600">
                  Investigate highly ranked features in the SHAP analysis for correlation with {sensitiveAttribute} and consider removing them.
                </CardContent>
              </Card>

              <Card className="bg-card border-border print:border print:border-gray-300">
                <CardHeader className="pb-3">
                  <AlertTriangle className="h-8 w-8 text-warning mb-2 print:text-amber-500" />
                  <CardTitle className="text-base font-bold">Audit Training Pipeline</CardTitle>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground leading-relaxed print:text-gray-600">
                  Implement fairness constraints during model training using fairlearn&apos;s GridSearch algorithm.
                </CardContent>
              </Card>
            </div>
          </section>

          {/* Footer with "Run New Audit" link */}
          <div className="text-center pt-6 pb-10 print:hidden">
            <Link href="/">
              <Button variant="outline" size="lg" className="border-primary text-primary hover:bg-primary/10">
                ← Run a New Audit
              </Button>
            </Link>
          </div>
          
        </div>
      </main>
    </div>
  );
}
